add subgraph support
Nymphium/lua-graphviz pull request #1
Opened 2017-03-31 08:40 UTC by yuliying

add subgraph support

2017-03-31 15:12 UTC, Nymphium requested changes

2017-03-31 15:12 UTC, Nymphium commented on graphviz.lua
> +	addsubgraph = function(self , subgraphname)
method name should be `subgraph`, like `edge`, `node`.

2017-03-31 15:12 UTC, Nymphium commented on graphviz.lua
> +	end ,
remove space  between`end`  `,`

2017-03-31 15:12 UTC, Nymphium commented on graphviz.lua
> +		__subgraphs = {} ,
field name should be `subgraphs`, like `edges` and `nodes`.

2017-03-31 15:12 UTC, Nymphium commented on graphviz.lua
> +		--indent
in this case `delimiter` is fixed by `"\n"` so the argument is not needed.
More to say, this `split` should be like this:

```lua
local function split(str)
	if not str:match("\n$") then
		str = str .. "\n"
	end

	local ret = {}

	for w in str:gmatch("(.-)\n") do
		table.insert(ret, w)
	end

	return ret
end

local lines = split(src)
......
```

2017-04-01 02:32 UTC, yuliying commented on graphviz.lua
> +		--indent
yes , this split functions looks great.

2017-04-01 02:42 UTC, yuliying commented
all you mentioned fixed .

2017-04-01 05:06 UTC, Nymphium requested changes
finally please revise this

2017-04-01 05:06 UTC, Nymphium commented on graphviz.lua
>  		--indent
remove unneeded comment

2017-04-01 05:06 UTC, Nymphium commented on graphviz.lua
> +		subgraphs = {} ,
remove a space between `{}` and `,`

2017-04-01 05:23 UTC, Nymphium commented
:+1:

2017-04-01 05:23 UTC, merged